name: Rebuild OpenWrt

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - foo/bar

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

        #    - uses: jakejarvis/s3-sync-action@master
        #      with:
        #        args: --acl public-read --follow-symlinks --delete
        #      env:
        #        AWS_S3_BUCKET: test
        #        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #        AWS_S3_ENDPOINT: https://images.aparcar.org
        #        SOURCE_DIR: rebuild/
    - name: sanitize target
      run: echo ::set-env name=TARGET_SANI::$(echo ${{ matrix.target }} | tr "/" "_")

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.TARGET_SANI }}
        path: rebuild//
